- name: Add Phusion Passenger repo key
  apt_key: url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x561F9B9CAC40B2F7 state=present
  sudo: yes

- name: Install packages to enable apt over HTTPS
  action: apt pkg={{item}} state=installed update_cache=true
  sudo: yes
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Add Phusion Passenger repo
  apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main'
  sudo: yes

- name: Install nginx-extras and passenger
  action: apt pkg={{item}} state=installed update_cache=true
  sudo: yes
  with_items:
    # note: Passenger repo has it's own nginx-extras package.
    - nginx-extras
    - passenger
